[tool.briefcase]
project_name = "Testbed"
bundle = "org.beeware"
version = "0.0.1"
url = "https://beeware.org"
license = "BSD license"
author = 'Russell Keith-Magee'
author_email = "russell@beeware.org"

[tool.briefcase.app.testbed]
formal_name = "Testbed"
description = "A testbed for the Apple Support packages."
icon = "src/testbed/resources/testbed"
sources = ['src/testbed']
requires = [
]

[tool.briefcase.app.testbed.macOS]
requires = [
    "rubicon-objc",
    "std-nslog",
]
support_package = "../Python-Apple-support/dist/Python-3.11-macOS-support.custom.tar.gz"
# template = "../../templates/briefcase-macOS-Xcode-template"

[tool.briefcase.app.testbed.linux]
supported = false

[tool.briefcase.app.testbed.windows]
supported = false

# Mobile deployments
[tool.briefcase.app.testbed.iOS]
requires = [
    "rubicon-objc",
    "std-nslog",
]
support_package = "../Python-Apple-support/dist/Python-3.11-iOS-support.custom.tar.gz"
# template = "../../templates/briefcase-iOS-Xcode-template"

[tool.briefcase.app.testbed.android]
supported = false
