[tool.briefcase]
project_name = "Testbed"
bundle = "org.beeware"
version = "0.0.1"
url = "https://beeware.org"
license = "BSD license"
author = 'Russell Keith-Magee'
author_email = "russell@beeware.org"

[tool.briefcase.app.testbed]
formal_name = "Testbed"
description = "A testbed for the Apple Support packages."
icon = "src/testbed/resources/testbed"
sources = ["src/testbed"]
test_sources = ["tests"]

requires = [
    "cryptography",
    "lru_dict",
    "pillow",
    "numpy",
    "pandas",
]
test_requires = [
    "pytest",
]

# FIXME: Use the PR962-compatible branch
template_branch = "testcase2"

[tool.briefcase.app.testbed.macOS]
requires = [
    "rubicon-objc",
    "std-nslog",
]
# support_package = "../Python-Apple-support/dist/Python-3.8-macOS-support.custom.tar.gz"

[tool.briefcase.app.testbed.macOS.app]
# template = "../../templates/briefcase-macOS-app-template"

[tool.briefcase.app.testbed.macOS.Xcode]
# template = "../../templates/briefcase-macOS-Xcode-template"

[tool.briefcase.app.testbed.linux]
requires=[
    'pycairo',
    'pygobject',
]

[tool.briefcase.app.testbed.linux.appimage]
requires=[
    '--no-binary', ':all:'
]

system_requires = [
    # Required for GTK/PyGObject tests
    'gir1.2-gtk-3.0',
    'libgirepository1.0-dev',
    # Required for pycairo
    'libcairo2-dev',
    # Required for Pillow
    'libjpeg-dev',
    'libpng-dev',
    'libtiff-dev',
    # Required to install Rust
    'curl',
    'libssl-dev',
]

linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

dockerfile_extra_content = """
# Install Rust (required for cryptography)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/brutus/.cargo/bin:${PATH}"
"""

# support_package = "../Python-linux-support/dist/Python-3.10-linux-x86_64-support.custom.tar.gz"
# template = "../../templates/briefcase-linux-appimage-template"

[tool.briefcase.app.testbed.linux.flatpak]
# template = "../../templates/briefcase-linux-flatpak-template"

[tool.briefcase.app.testbed.windows]
requires = [
    "pythonnet>=3.0.0rc6",
    # Windows doesn't provide the zoneinfo TZ database; use the Python provided one
    "tzdata",
]

[tool.briefcase.app.testbed.windows.app]
# template = "../../templates/briefcase-windows-app-template"

[tool.briefcase.app.testbed.windows.VisualStudio]
# template = "../../templates/briefcase-windows-VisualStudio-template"

# Mobile deployments
[tool.briefcase.app.testbed.iOS]
requires = [
    "rubicon-objc",
    "std-nslog",
]
# support_package = "../Python-Apple-support/dist/Python-3.8-iOS-support.custom.tar.gz"
# template = "../../templates/briefcase-iOS-Xcode-template"

[tool.briefcase.app.testbed.android]
requires = [
    "rubicon-java",
    # Android doesn't provide the zoneinfo TZ database; use the Python provided one
    "tzdata",
]
# support_package = "../Python-Android-support/dist/Python-3.10-Android-support.custom.zip"
# template = "../../templates/briefcase-Android-gradle-template"

[tool.isort]
profile = "black"
split_on_trailing_comma = true
combine_as_imports = true
