[tool.briefcase]
project_name = "Testbed"
bundle = "org.beeware"
version = "0.0.1"
url = "https://beeware.org"
license = "BSD license"
author = 'Russell Keith-Magee'
author_email = "russell@beeware.org"

[tool.briefcase.app.testbed]
formal_name = "Testbed"
description = "A testbed for the Apple Support packages."
icon = "src/testbed/resources/testbed"
sources = ['src/testbed']
requires = [
]

[tool.briefcase.app.testbed.macOS]
requires = [
    "rubicon-objc",
    "std-nslog",
]
support_package = "../Python-Apple-support/dist/Python-3.10-macOS-support.custom.tar.gz"
# template = "../../templates/briefcase-macOS-Xcode-template"

[tool.briefcase.app.testbed.linux]
requires=[
    'pycairo',
    'pygobject',
    'pillow',
]

[tool.briefcase.app.testbed.linux.appimage]
requires=[
    '--no-binary', 'pillow'
]

system_requires = [
    # Required for GTK/PyGObject tests
    'gir1.2-gtk-3.0',
    'libgirepository1.0-dev',
    # Required for pycairo
    'libcairo2-dev',
    # Required for Pillow
    'libjpeg-dev',
    'libpng-dev',
    'libtiff-dev',
]

linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

support_package = "../Python-linux-support/dist/Python-3.10-linux-x86_64-support.custom.tar.gz"
# template = "../../templates/briefcase-linux-appimage-template"

[tool.briefcase.app.testbed.linux.flatpak]

# template = "../../templates/briefcase-linux-flatpak-template"

[tool.briefcase.app.testbed.windows]
supported = false

# Mobile deployments
[tool.briefcase.app.testbed.iOS]
requires = [
    "rubicon-objc",
    "std-nslog",
]
support_package = "../Python-Apple-support/dist/Python-3.10-iOS-support.custom.tar.gz"
# template = "../../templates/briefcase-iOS-Xcode-template"

[tool.briefcase.app.testbed.android]
requires = [
    "rubicon-java",
    # Android doesn't provide the zoneinfo TZ database; use the Python provided one
    "tzdata",
]
support_package = "../Python-Android-support/dist/Python-3.10-Android-support.custom.zip"
# template = "../../templates/briefcase-Android-gradle-template"
